### ISSUE TITLE
支持自动添加好友等功能

### ISSUE THREAD

**Issue by chucai** [algorithmdaybyday/assistant#4]
实现拉群小助手的基本功能： 自动添加好友，拉群功能

自动添加好友功能： 就是别人加机器人好友，留言是我要加群，然后机器人自动加该人为好友，并且邀请该朋友加入算法第6群

**Comment by xuan1992** [comment]
我来试试吧！

**Comment by chucai** [comment]
赞！ 谢谢 @xuan1992  认领该任务。

**Comment by suisuiwudi** [comment]
我写了读取验证信息自动加好友提到pr了，拉群没写

**Comment by chucai** [comment]
恩 还需要实现拉群功能~
